apiVersion: v2
name: blockasaurus
description: Fast and lightweight DNS proxy as ad-blocker for local network
type: application
version: 0.34.37
appVersion: "v0.34.37"
keywords:
  - dns
  - adblock
  - privacy
  - proxy
home: https://github.com/chrissnell/blockasaurus
sources:
  - https://github.com/chrissnell/blockasaurus
maintainers:
  - name: chrissnell
